language: go
arch:
  - amd64
  - arm64
go:
  - 1.14.x
  - 1.13.x
install:
  - go get github.com/triplewz/cryptogm
script:
  - go test -v ./elliptic/sm2curve/
  - go test -v ./sm/sm2/
  - go test -v ./sm/sm3/
  - go test -v ./sm/sm4/
  - go test -v ./sm/sm9/
